language: node_js
branches:
  only:
    - master
cache:
  directories:
    - tests/elm-stuff/build-artifacts
    - $(npm config get prefix)/bin
    - $(npm root -g)
node_js:
  - "6.9"
install:
  - npm install -g elm@0.18 elm-test@0.18.2
script:
  - elm-test
